[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
oito_core = { path = "../oito_core" }
js-sys = "^0.3"
wasm-bindgen = "^0.2"

[dependencies.web-sys]
version = "0.3"
features = []